---
title: "Assignment 2"
format: html
editor: visual
---

## Library and Packages

```{r}

library(dataRetrieval) 
library(tidyverse)
library(lubridate)

```

## Data Retrieval

```{r}

siteNumbers <- c("14211720", "14211010", "14166000")
parameterCd <- "00010"  # water temperature
startDate <- "2010-01-01"
endDate <- "2023-12-31"

temp_data <- readNWISdv(siteNumbers, parameterCd, startDate, endDate)

```

## Data Prep

```{r}

# rename columns for clarity
colnames(temp_data)[4] <- "temp_C"
# extract some date info for use later
temp_data$month = month(temp_data$Date, label=TRUE)
temp_data$year = year(temp_data$Date)

# check by plotting
ggplot(temp_data, aes(x=Date, y=temp_C, color=site_no)) +
  geom_line() +
  labs(title="Stream Temperature at Willamette River Sites",
       x="Date", y="Temperature (°C)", color="Site Number") +
  theme_minimal()

```

## Summary Statistics

```{r}

temp_summary <- temp_data %>%
  group_by(site_no) %>%
  summarize(
    mean_temp = mean(temp_C, na.rm = TRUE),
    max_temp = max(temp_C, na.rm = TRUE),
    min_temp = min(temp_C, na.rm = TRUE)
  )

```

## andddd save

```{r}

write_csv(temp_data, "willamette_temp.csv")

```
